import React, { type ReactNode } from "react";
import { Activity, Building2, ChevronRight, CircleDollarSign, FileText, LayoutDashboard, Menu, PanelLeftClose, PanelLeftOpen, Settings, ShieldCheck, Users, X, Boxes } from "lucide-react";
import type { PlatformAdminSession } from "../types";
import { Avatar, cn, IconButton, StatusBadge } from "./ui";

export type AppRoute = "dashboard" | "tenants" | "subscriptions" | "modules" | "admins" | "audit" | "settings";

const groups: Array<{ label: string; items: Array<{ id: AppRoute; label: string; icon: typeof LayoutDashboard }> }> = [
  { label: "Overview", items: [{ id: "dashboard", label: "Dashboard", icon: LayoutDashboard }] },
  { label: "Manage", items: [{ id: "tenants", label: "Tenants", icon: Building2 }, { id: "subscriptions", label: "Subscriptions", icon: CircleDollarSign }, { id: "modules", label: "Modules & access", icon: Boxes }] },
  { label: "Platform", items: [{ id: "admins", label: "Platform admins", icon: Users }, { id: "audit", label: "Audit log", icon: Activity }, { id: "settings", label: "Settings", icon: Settings }] },
];

const routeLabels: Record<AppRoute, string> = { dashboard: "Dashboard", tenants: "Tenants", subscriptions: "Subscriptions", modules: "Modules & access", admins: "Platform admins", audit: "Audit log", settings: "Settings" };

export function AppShell({ route, onRouteChange, session, mode, children }: { route: AppRoute; onRouteChange: (route: AppRoute) => void; session: PlatformAdminSession; mode: "fixtures" | "live"; children: ReactNode }) {
  const [mobileOpen, setMobileOpen] = React.useState(false);
  const [collapsed, setCollapsed] = React.useState(false);

  return <div className="min-h-screen bg-[#f5f7f8] text-slate-900"><aside className={cn("fixed inset-y-0 left-0 z-40 hidden flex-col bg-[#15252f] text-white transition-all lg:flex", collapsed ? "w-[76px]" : "w-[248px]")}><SidebarContent route={route} collapsed={collapsed} onRouteChange={onRouteChange} onCollapse={() => setCollapsed(!collapsed)} /></aside>{mobileOpen ? <div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-[#08131a]/50" onClick={() => setMobileOpen(false)} /><aside className="relative flex h-full w-[280px] flex-col bg-[#15252f] text-white"><SidebarContent route={route} collapsed={false} onRouteChange={(next) => { onRouteChange(next); setMobileOpen(false); }} onCollapse={() => setMobileOpen(false)} mobile /></aside></div> : null}<main className={cn("min-h-screen transition-all", collapsed ? "lg:pl-[76px]" : "lg:pl-[248px]")}><header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-slate-200 bg-white/90 px-4 backdrop-blur sm:px-7"><div className="flex items-center gap-3"><IconButton label="Open navigation" className="lg:hidden" onClick={() => setMobileOpen(true)}><Menu className="h-5 w-5" /></IconButton><div className="hidden items-center gap-2 text-sm text-slate-400 sm:flex"><span>Platform</span><ChevronRight className="h-4 w-4" /><span className="font-semibold text-slate-700">{routeLabels[route]}</span></div><div className="sm:hidden"><p className="text-sm font-bold text-slate-900">{routeLabels[route]}</p><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#13845e]">Platform control</p></div></div><div className="flex items-center gap-3"><StatusBadge label={mode === "fixtures" ? "Fixture mode" : "Live mode"} tone={mode === "fixtures" ? "warning" : "success"} /><div className="hidden h-8 w-px bg-slate-200 sm:block" /><div className="hidden items-center gap-2.5 sm:flex"><Avatar name={session.name} size="sm" /><div><p className="text-xs font-bold text-slate-800">{session.name}</p><p className="text-[10px] text-slate-500">{session.role.replace("platform_", "")}</p></div></div></div></header><div className="mx-auto max-w-[1600px] px-4 py-6 sm:px-7 sm:py-8">{children}</div></main></div>;
}

function SidebarContent({ route, collapsed, onRouteChange, onCollapse, mobile = false }: { route: AppRoute; collapsed: boolean; onRouteChange: (route: AppRoute) => void; onCollapse: () => void; mobile?: boolean }) {
  return <><div className={cn("flex h-[72px] items-center border-b border-white/10", collapsed ? "justify-center px-3" : "justify-between px-5")}><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#8ee0bd] text-[#123a2c]"><ShieldCheck className="h-5 w-5" /></div>{!collapsed ? <div><p className="text-sm font-bold tracking-tight">AtollCargo</p><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#8ee0bd]">Platform admin</p></div> : null}</div>{mobile ? <IconButton label="Close navigation" className="text-white/70 hover:bg-white/10 hover:text-white" onClick={onCollapse}><X className="h-4 w-4" /></IconButton> : <IconButton label={collapsed ? "Expand navigation" : "Collapse navigation"} className="text-white/60 hover:bg-white/10 hover:text-white" onClick={onCollapse}>{collapsed ? <PanelLeftOpen className="h-4 w-4" /> : <PanelLeftClose className="h-4 w-4" />}</IconButton>}</div><nav className="no-scrollbar flex-1 overflow-y-auto px-3 py-5">{groups.map((group) => <div key={group.label} className="mb-6">{!collapsed ? <p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-white/35">{group.label}</p> : null}<div className="space-y-1">{group.items.map((item) => { const Icon = item.icon; const active = route === item.id; return <button key={item.id} title={collapsed ? item.label : undefined} onClick={() => onRouteChange(item.id)} className={cn("group flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-semibold transition", active ? "bg-white/10 text-[#9de6c4]" : "text-white/60 hover:bg-white/5 hover:text-white", collapsed && "justify-center px-0")}><Icon className={cn("h-[17px] w-[17px] shrink-0", active ? "text-[#9de6c4]" : "text-white/50 group-hover:text-white/80")} />{!collapsed ? <span>{item.label}</span> : null}{!collapsed && active ? <span className="ml-auto h-1.5 w-1.5 rounded-full bg-[#9de6c4]" /> : null}</button>; })}</div></div>)}</nav><div className={cn("border-t border-white/10 p-4", collapsed && "px-3")}><div className={cn("rounded-xl bg-white/5 p-3", collapsed && "flex justify-center p-2")}><div className="flex items-center gap-2.5"><FileText className="h-4 w-4 shrink-0 text-[#9de6c4]" />{!collapsed ? <div><p className="text-xs font-semibold text-white/80">Admin handbook</p><p className="mt-0.5 text-[10px] text-white/40">Policies & workflows</p></div> : null}</div></div></div></>;
}
