import { Boxes, CheckCircle2, CircleDollarSign, LockKeyhole, Sparkles } from "lucide-react";
import type { PlatformModule, PlatformSnapshot } from "../types";
import { money, titleCase } from "../lib/format";
import { Button, ProgressBar, SectionCard, StatusBadge, TableCell, TableHead, TableHeaderCell, TableRow, Toggle } from "../components/ui";

export function ModulesPage({ snapshot, onModuleToggle }: { snapshot: PlatformSnapshot; onModuleToggle: (tenantId: string, moduleId: string, enabled: boolean) => void }) {
  return <><div className="mb-7 flex items-end justify-between gap-4"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[0.14em] text-[#13845e]">Product access</p><h1 className="text-2xl font-bold tracking-[-0.02em] text-slate-950 sm:text-3xl">Modules & access</h1><p className="mt-2 text-sm text-slate-500">Control which platform capabilities are available to each business profile.</p></div><Button variant="secondary"><Sparkles className="h-4 w-4" />Manage catalog</Button></div><div className="grid gap-4 sm:grid-cols-3"><ModuleStat label="Available modules" value={snapshot.modules.filter((module) => module.status !== "sunset").length} detail="Across the product catalog" icon={<Boxes className="h-5 w-5" />} /><ModuleStat label="Enabled entitlements" value={snapshot.modules.reduce((sum, module) => sum + module.enabledFor, 0)} detail="Tenant-module relationships" icon={<CheckCircle2 className="h-5 w-5" />} /><ModuleStat label="Add-on value" value={money(snapshot.modules.reduce((sum, module) => sum + module.monthlyValue, 0))} detail="Monthly module revenue" icon={<CircleDollarSign className="h-5 w-5" />} /></div><SectionCard className="mt-6" title="Module catalog" description="Availability and adoption across active tenants."><div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">{snapshot.modules.map((module) => <ModuleCard key={module.id} module={module} />)}</div></SectionCard><SectionCard className="mt-6" title="Tenant entitlements" description="Use the controls to enable or disable modules for an individual tenant."><div className="overflow-x-auto"><table className="w-full min-w-[980px]"><TableHead><tr><TableHeaderCell>Business profile</TableHeaderCell>{snapshot.modules.map((module) => <TableHeaderCell className="text-center" key={module.id}><span className="inline-block max-w-[92px]">{module.name}</span></TableHeaderCell>)}</tr></TableHead><tbody>{snapshot.tenants.filter((tenant) => tenant.status !== "blocked").map((tenant) => <TableRow key={tenant.id}><TableCell><span className="font-bold text-slate-800">{tenant.name}</span><span className="mt-0.5 block text-xs text-slate-400">{titleCase(tenant.status)} · {tenant.users} users</span></TableCell>{snapshot.modules.map((module) => <TableCell className="text-center" key={module.id}><div className="flex justify-center"><Toggle checked={tenant.enabledModules.includes(module.id)} onChange={(enabled) => onModuleToggle(tenant.id, module.id, enabled)} label={`${enabledLabel(tenant.enabledModules.includes(module.id), module.name)} for ${tenant.name}`} /></div></TableCell>)}</TableRow>)}</tbody></table></div></SectionCard></>;
}

function enabledLabel(enabled: boolean, module: string) { return `${enabled ? "Disable" : "Enable"} ${module}`; }
function ModuleStat({ label, value, detail, icon }: { label: string; value: number | string; detail: string; icon: React.ReactNode }) { return <div className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#dff8eb] text-[#08754e]">{icon}</span><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold tracking-[-0.03em] text-slate-950">{value}</p></div></div><p className="mt-4 text-xs text-slate-500">{detail}</p></div>; }
function ModuleCard({ module }: { module: PlatformModule }) { return <div className="rounded-xl border border-slate-200 bg-slate-50/60 p-4"><div className="flex items-start justify-between gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-[#13845e] shadow-sm"><Boxes className="h-4 w-4" /></div><StatusBadge label={module.status} tone={module.status === "beta" ? "warning" : module.status === "sunset" ? "danger" : "success"} /></div><h3 className="mt-4 text-sm font-bold text-slate-800">{module.name}</h3><p className="mt-1 min-h-[40px] text-xs leading-5 text-slate-500">{module.description}</p><div className="mt-4 flex items-center justify-between text-xs"><span className="font-semibold text-slate-500">{module.enabledFor} tenants</span><span className="font-bold text-slate-700">{module.adoption}% adoption</span></div><div className="mt-2"><ProgressBar value={module.adoption} color={module.status === "beta" ? "bg-[#d58a1a]" : "bg-[#16845d]"} /></div>{module.status === "beta" ? <p className="mt-3 flex items-center gap-1.5 text-[11px] font-semibold text-amber-700"><LockKeyhole className="h-3 w-3" />Limited release</p> : null}</div>; }
